# Hyprlock configuration with vague theme
general {
    disable_loading_bar = true
    grace = 300
    hide_cursor = true
    no_fade_in = false
}

# Background
background {
    monitor =
    path = ~/.config/arch-config/modules/loopy/dotfiles/swaybg/bg.png
    blur_passes = 3 
    blur_size = 4 
}

# Input field
input-field {
    monitor = DP-1
    size = 160, 30
    position = 0, -20
    dots_center = true
    fade_on_empty = true
    font_color = rgba(ffffff99)
    inner_color = rgba(e2b79966)
    outer_color = rgba(00000066)
    outline_thickness = 2
    placeholder_text = 
    shadow_passes = 0 
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(e98381ff)
    shadow_passes = 2
    shadow_size = 0.5
    font_size = 32
    font_family = GohuFont uni14 Nerd Font Propo
    position = 0, 24
    halign = center
    valign = center
}

# User
label {
    monitor =
    text = ♥ Woof!
    color = rgba(ffffffff)
    shadow_passes = 2
    shadow_size = 1
    font_size = 16
    font_family = GohuFont uni14 Nerd Font Mono
    position = 0, 60
    halign = center
    valign = center
}
